name: GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: containers.ligo.org/lscsoft/bilby/v2-bilby-python311
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: install
        run: python -m pip install .
      - name: Run jupyter notebooks
        run: |
          python -m ipykernel install
          cd examples/tutorials
          jupyter nbconvert --to notebook --execute *.ipynb --output-dir ../../docs
          cd -
      - name: Build docs
        run: |
          cd docs
          make clean
          make html
          cd -
      # Upload the build docs as an artifact until we expose the pages
      - uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
